//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lineups
    {
        public long ID { get; set; }
        public long ID_Performer { get; set; }
        public long ID_Musician { get; set; }
    
        public virtual Musicians Musicians { get; set; }
        public virtual Performers Performers { get; set; }
    }
}
