//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusCatalog
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    
    public partial class Musicians
    {
        public Musicians()
        {
            this.Lineups = new ObservableCollection<Lineups>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public Nullable<short> YearBorn { get; set; }
        public Nullable<short> YearDied { get; set; }
        public Nullable<long> PID { get; set; }
    
        public virtual ObservableCollection<Lineups> Lineups { get; set; }
    }
}
