//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Songs
    {
        public long PID { get; set; }
        public long AID { get; set; }
        public long SID { get; set; }
        public byte SN { get; set; }
        public string SName { get; set; }
        public string STime { get; set; }
        public string SInfo { get; set; }
        public Nullable<byte> SRate { get; set; }
    
        public virtual Albums Albums { get; set; }
    }
}
