//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusCatalog.Model
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    
    public partial class Albums
    {
        public Albums()
        {
            this.Songs = new ObservableCollection<Songs>();
        }
    
        public long PID { get; set; }
        public long AID { get; set; }
        public string Album { get; set; }
        public short AYear { get; set; }
        public string ATime { get; set; }
        public string AInfo { get; set; }
        public Nullable<byte> ARate { get; set; }
    
        public virtual Performers Performers { get; set; }
        public virtual ObservableCollection<Songs> Songs { get; set; }
    }
}
