//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusCatalog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumsWithoutTotalTimeView
    {
        public short ReleaseYear { get; set; }
        public string Name { get; set; }
        public string TotalTime { get; set; }
        public string PerformerName { get; set; }
        public long ID { get; set; }
    }
}
