//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusCatalog.Model
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    
    public partial class Genre
    {
        public Genre()
        {
            this.Performers = new ObservableCollection<Performer>();
        }
    
        public byte ID { get; set; }
        public string Name { get; set; }

        public virtual ObservableCollection<Performer> Performers { get; set; }
    }
}
