//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusCatalog.Model
{
    public partial class Lineup
    {
        public long PerformerID { get; set; }
        public long MusicianID { get; set; }
        public short? YearStart { get; set; }
        public short? YearEnd { get; set; }
    
        public virtual Musician Musician { get; set; }
        public virtual Performer Performer { get; set; }
    }
}
