//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusCatalog.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MusCatEntities : DbContext
    {
        public MusCatEntities()
            : base("name=MusCatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Album> Albums { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<Lineup> Lineups { get; set; }
        public DbSet<Musician> Musicians { get; set; }
        public DbSet<Performer> Performers { get; set; }
        public DbSet<Song> Songs { get; set; }
        public DbSet<AlbumsWithEmptySongsView> AlbumsWithEmptySongsViews { get; set; }
        public DbSet<AlbumsWithoutTotalTimeView> AlbumsWithoutTotalTimeViews { get; set; }
        public DbSet<EmptyAlbumsView> EmptyAlbumsViews { get; set; }
    
        public virtual int DeleteAlbumByID(Nullable<int> original_AID)
        {
            var original_AIDParameter = original_AID.HasValue ?
                new ObjectParameter("Original_AID", original_AID) :
                new ObjectParameter("Original_AID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAlbumByID", original_AIDParameter);
        }
    
        public virtual int DeletePerformerByID(Nullable<int> original_PID)
        {
            var original_PIDParameter = original_PID.HasValue ?
                new ObjectParameter("Original_PID", original_PID) :
                new ObjectParameter("Original_PID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletePerformerByID", original_PIDParameter);
        }
    
        public virtual ObjectResult<SelectPerformerByLetter_Result> SelectPerformerByLetter(string lETTER)
        {
            var lETTERParameter = lETTER != null ?
                new ObjectParameter("LETTER", lETTER) :
                new ObjectParameter("LETTER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectPerformerByLetter_Result>("SelectPerformerByLetter", lETTERParameter);
        }
    
        public virtual ObjectResult<SelectRestOfPerformers_Result> SelectRestOfPerformers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectRestOfPerformers_Result>("SelectRestOfPerformers");
        }
    
        public virtual ObjectResult<SelectSongsInTimeInterval_Result> SelectSongsInTimeInterval(string lOW_TIME, string hIGH_TIME)
        {
            var lOW_TIMEParameter = lOW_TIME != null ?
                new ObjectParameter("LOW_TIME", lOW_TIME) :
                new ObjectParameter("LOW_TIME", typeof(string));
    
            var hIGH_TIMEParameter = hIGH_TIME != null ?
                new ObjectParameter("HIGH_TIME", hIGH_TIME) :
                new ObjectParameter("HIGH_TIME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectSongsInTimeInterval_Result>("SelectSongsInTimeInterval", lOW_TIMEParameter, hIGH_TIMEParameter);
        }
    }
}
