//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusCatalog.Model
{
    using System.Collections.Generic;
    
    public partial class Musician
    {
        public Musician()
        {
            Lineups = new HashSet<Lineup>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public short? YearBorn { get; set; }
        public short? YearDied { get; set; }
        public long? PerformerID { get; set; }
    
        public virtual ICollection<Lineup> Lineups { get; set; }
    }
}
