//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusCatalog.Model
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    
    public partial class Performers
    {
        public Performers()
        {
            this.Albums = new ObservableCollection<Albums>();
            this.Lineups = new ObservableCollection<Lineups>();
        }
    
        public long PID { get; set; }
        public string Performer { get; set; }
        public string Country { get; set; }
        public string Info { get; set; }
    
        public virtual ObservableCollection<Albums> Albums { get; set; }
        public virtual ObservableCollection<Lineups> Lineups { get; set; }
    }
}
