//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusCatalog.Model
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    
    public partial class Performer
    {
        public Performer()
        {
            this.Albums = new ObservableCollection<Album>();
            this.Lineups = new ObservableCollection<Lineup>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public Nullable<byte> CountryID { get; set; }

        public virtual ObservableCollection<Album> Albums { get; set; }
        public virtual Country Country { get; set; }
        public virtual ObservableCollection<Lineup> Lineups { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
