//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusCatalog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performer
    {
        public Performer()
        {
            this.Albums = new HashSet<Album>();
            this.Lineups = new HashSet<Lineup>();
            this.Genres = new HashSet<Genre>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public Nullable<byte> CountryID { get; set; }
    
        public virtual ICollection<Album> Albums { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Lineup> Lineups { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
    }
}
